import { z } from 'zod'

/*
 * The fact-set contract. Every later layer reads this, so it is the one place
 * in the vertical slice worth being slow about.
 *
 * Two properties are load-bearing and easy to lose in a refactor:
 *
 * 1. The branded primitives are SECURITY CONTROLS, not formatting preferences.
 *    {@link Slug} becomes a directory name and {@link RepoPath} becomes a path
 *    argument, so their regexes are what keep a crafted fact-set from escaping
 *    the content directory.
 * 2. Every object is STRICT. A non-strict object silently drops an unexpected
 *    key, which turned a real defense into decoration: a `manual` selection
 *    carrying a fabricated `scores` object parsed clean because the extra key
 *    was stripped rather than rejected. The fact-set is generated by a model, so
 *    an unmodelled key means drift and has to be loud.
 * 3. Every datetime uses `z.iso.datetime()` with default options, which REJECTS
 *    a zone offset. Git committer dates arrive as `+10:00` and the GitHub API
 *    returns `Z`; forcing the schema to accept only `Z` makes the collector
 *    normalize at its boundary instead of leaving two clock conventions to meet
 *    inside the `knownAt` comparison, where a timezone bug reads like a logic bug.
 */

/** A full 40-char git object name; short SHAs are rejected because they are not stable. */
export const Sha = z.string().regex(/^[0-9a-f]{40}$/, 'not a 40-char hex sha').brand<'Sha'>()

/** Directory-safe id. Becomes a path segment, so `/` and `..` must never parse. */
export const Slug = z.string().regex(/^[a-z0-9][a-z0-9-]{0,80}$/, 'not a slug').brand<'Slug'>()

/** `owner/name`, the shape `gh` and permalink construction both expect. */
export const RepoNm = z.string().regex(/^[\w.-]+\/[\w.-]+$/, 'not owner/name').brand<'RepoNm'>()

/** A path inside the target repo. The `..` check is separate from the regex because `.` is legal in a filename. */
export const RepoPath = z
  .string()
  .regex(/^[\w./-]+$/, 'illegal character in path')
  .refine((p) => !p.split('/').includes('..'), 'path traversal')
  .brand<'RepoPath'>()

export const PosInt = z.number().int().positive()

/** UTC-only ISO 8601. The offset rejection is the normalization guard described above. */
const Utc = z.iso.datetime()

/** Score axes only exist for ranked selection; a hand-picked incident must not fabricate them. */
const Selection = z.discriminatedUnion('kind', [
  z.strictObject({ kind: z.literal('manual'), reason: z.string().min(1) }),
  z.strictObject({
    kind: z.literal('ranked'),
    scores: z.strictObject({
      novelty: z.number().int().min(0).max(3),
      evidence: z.number().int().min(0).max(3),
      consequence: z.number().int().min(0).max(3),
      explicability: z.number().int().min(0).max(3),
    }),
    total: z.number().int(),
    winningAxis: z.string(),
    rejectedCount: z.number().int().nonnegative(),
  }),
])

export const Incident = z.strictObject({
  id: Slug,
  signal: z.enum(['git-trace']),
  selection: Selection,
  // No localPath: where the clone happens to sit is runtime context, not a fact,
  // and it is on the never-rendered list.
  repo: z.strictObject({
    nameWithOwner: RepoNm,
    defaultBranch: z.string().min(1),
    spdxLicense: z.string(),
  }),
  anchorSha: Sha,
  knownAt: Utc,
  commits: z.array(z.strictObject({ sha: Sha, committedAt: Utc, subject: z.string() })),
  discussions: z.array(
    z.strictObject({
      kind: z.enum(['issue', 'pr']),
      number: PosInt,
      createdAt: Utc,
      quotes: z.array(
        z.strictObject({
          excerpt: z.string(),
          bodyHash: z.string().length(64),
          offset: z.number().int().nonnegative(),
          author: z.string(),
          commentId: PosInt,
          createdAt: Utc,
          fetchedAt: Utc,
        }),
      ),
    }),
  ),
  codeQuotes: z.array(
    z
      .object({
        path: RepoPath,
        atSha: Sha,
        atShaCommittedAt: Utc,
        startLine: PosInt,
        endLine: PosInt,
        text: z.string(),
      })
      .refine((q) => q.startLine <= q.endLine, 'reversed line range'),
  ),
  diff: z
    .object({ beforeSha: Sha, afterSha: Sha, path: RepoPath, hunk: z.string() })
    .nullable(),
  revealedLater: z.array(
    z.strictObject({
      at: Utc,
      what: z.string().min(1),
      evidence: z.discriminatedUnion('kind', [
        z.strictObject({ kind: z.literal('commit'), sha: Sha }),
        z.strictObject({ kind: z.literal('discussion'), number: PosInt, commentId: PosInt.optional() }),
      ]),
    }),
  ),
})

/** One of the five content-addressed id forms; parsed by {@link parseFactRef}, never by an index. */
export const FactRef = z.string().min(1)

const Sentence = z.strictObject({ text: z.string().min(1), cites: z.array(FactRef) })

/*
 * A prose block's unit is the SENTENCE, because the spec puts each [n]
 * immediately after the sentence it supports. A flat `text` + `cites[]` cannot
 * express that mapping, so the renderer would have no choice but to cluster
 * markers at the paragraph end.
 */
const Block = z.discriminatedUnion('type', [
  z.strictObject({ type: z.literal('prose'), sentences: z.array(Sentence).min(1) }),
  z.strictObject({ type: z.literal('codeQuote'), ref: FactRef }),
  z.strictObject({ type: z.literal('personQuote'), ref: FactRef }),
  z.strictObject({ type: z.literal('diffBox') }),
  z.strictObject({ type: z.literal('timelineBox') }),
])

/**
 * Shape-only article schema. The rules that need the incident live in
 * {@link articleSchemaFor}; the one rule enforceable on the article alone is the
 * lede exemption, so it is checked here.
 */
export const Article = z
  .object({
    incidentId: Slug,
    lang: z.enum(['en']),
    persona: z.enum(['desk']),
    title: z.string().min(1).max(120),
    titleCites: z.array(FactRef).min(1),
    dek: z.string().min(1).max(240),
    dekCites: z.array(FactRef).min(1),
    publishedAt: Utc,
    updatedAt: Utc,
    blocks: z.array(Block),
    aftermath: z.array(z.strictObject({ text: z.string().min(1), ref: FactRef })),
  })
  .check((ctx) => {
    // The lede is blocks[0] POSITIONALLY. There is no lede flag, because a flag
    // is a constraint the constrained party gets to remove: a writer allowed to
    // set `lede: true` is a writer allowed to exempt any paragraph from citation.
    ctx.value.blocks.forEach((b, i) => {
      if (b.type !== 'prose' || i === 0) return
      if (!b.sentences.some((s) => s.cites.length >= 1)) {
        ctx.issues.push({
          code: 'custom',
          input: ctx.value,
          path: ['blocks', i],
          message: `prose block ${i} is not the lede and carries no cited sentence`,
        })
      }
    })
    if (ctx.value.updatedAt < ctx.value.publishedAt) {
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: ['updatedAt'],
        message: 'updatedAt is before publishedAt',
      })
    }
  })

export type Incident = z.infer<typeof Incident>
export type Article = z.infer<typeof Article>
export type Block = z.infer<typeof Block>
export type Sentence = z.infer<typeof Sentence>
