import { z } from 'zod'

import { datedFacts, incidentRefIndex, parseFactRef, revealedRefFor } from './facts'
import type { FactRefParsed } from './facts'

/*
 * The fact-set contract. Every later layer reads this, so it is the one place
 * in the vertical slice worth being slow about.
 *
 * Two properties are load-bearing and easy to lose in a refactor:
 *
 * 1. The branded primitives are SECURITY CONTROLS, not formatting preferences.
 *    {@link Slug} becomes a directory name and {@link RepoPath} becomes a path
 *    argument, so their regexes are what keep a crafted fact-set from escaping
 *    the content directory.
 * 2. Every object is STRICT. A non-strict object silently drops an unexpected
 *    key, which turned a real defense into decoration: a `manual` selection
 *    carrying a fabricated `scores` object parsed clean because the extra key
 *    was stripped rather than rejected. The fact-set is generated by a model, so
 *    an unmodelled key means drift and has to be loud.
 * 3. Every datetime uses `z.iso.datetime()` with default options, which REJECTS
 *    a zone offset. Git committer dates arrive as `+10:00` and the GitHub API
 *    returns `Z`; forcing the schema to accept only `Z` makes the collector
 *    normalize at its boundary instead of leaving two clock conventions to meet
 *    inside the `knownAt` comparison, where a timezone bug reads like a logic bug.
 */

/** A full 40-char git object name; short SHAs are rejected because they are not stable. */
export const Sha = z.string().regex(/^[0-9a-f]{40}$/, 'not a 40-char hex sha').brand<'Sha'>()

/** Directory-safe id. Becomes a path segment, so `/` and `..` must never parse. */
export const Slug = z.string().regex(/^[a-z0-9][a-z0-9-]{0,80}$/, 'not a slug').brand<'Slug'>()

/** `owner/name`, the shape `gh` and permalink construction both expect. */
export const RepoNm = z.string().regex(/^[\w.-]+\/[\w.-]+$/, 'not owner/name').brand<'RepoNm'>()

/** A path inside the target repo. The `..` check is separate from the regex because `.` is legal in a filename. */
export const RepoPath = z
  .string()
  .regex(/^[\w./-]+$/, 'illegal character in path')
  .refine((p) => !p.split('/').includes('..'), 'path traversal')
  .brand<'RepoPath'>()

export const PosInt = z.number().int().positive()

/** UTC-only ISO 8601. The offset rejection is the normalization guard described above. */
const Utc = z.iso.datetime()

/** Score axes only exist for ranked selection; a hand-picked incident must not fabricate them. */
const Selection = z.discriminatedUnion('kind', [
  z.strictObject({ kind: z.literal('manual'), reason: z.string().min(1) }),
  z.strictObject({
    kind: z.literal('ranked'),
    scores: z.strictObject({
      novelty: z.number().int().min(0).max(3),
      evidence: z.number().int().min(0).max(3),
      consequence: z.number().int().min(0).max(3),
      explicability: z.number().int().min(0).max(3),
    }),
    total: z.number().int(),
    winningAxis: z.string(),
    rejectedCount: z.number().int().nonnegative(),
  }),
])

export const Incident = z.strictObject({
  id: Slug,
  signal: z.enum(['git-trace']),
  selection: Selection,
  // No localPath: where the clone happens to sit is runtime context, not a fact,
  // and it is on the never-rendered list.
  repo: z.strictObject({
    nameWithOwner: RepoNm,
    defaultBranch: z.string().min(1),
    spdxLicense: z.string(),
  }),
  anchorSha: Sha,
  knownAt: Utc,
  commits: z.array(z.strictObject({ sha: Sha, committedAt: Utc, subject: z.string() })),
  discussions: z.array(
    z.strictObject({
      kind: z.enum(['issue', 'pr']),
      number: PosInt,
      createdAt: Utc,
      quotes: z.array(
        z.strictObject({
          excerpt: z.string(),
          bodyHash: z.string().length(64),
          offset: z.number().int().nonnegative(),
          author: z.string(),
          commentId: PosInt,
          createdAt: Utc,
          fetchedAt: Utc,
        }),
      ),
    }),
  ),
  codeQuotes: z.array(
    z
      .strictObject({
        path: RepoPath,
        atSha: Sha,
        atShaCommittedAt: Utc,
        startLine: PosInt,
        endLine: PosInt,
        text: z.string(),
      })
      .refine((q) => q.startLine <= q.endLine, 'reversed line range'),
  ),
  diff: z
    .strictObject({ beforeSha: Sha, afterSha: Sha, path: RepoPath, hunk: z.string() })
    .nullable(),
  revealedLater: z.array(
    z.strictObject({
      at: Utc,
      what: z.string().min(1),
      evidence: z.discriminatedUnion('kind', [
        z.strictObject({ kind: z.literal('commit'), sha: Sha }),
        z.strictObject({ kind: z.literal('discussion'), number: PosInt, commentId: PosInt.optional() }),
      ]),
    }),
  ),
})
  .check((ctx) => {
    const { knownAt } = ctx.value
    /*
     * The knownAt partition is what makes the "time machine" claim true: the
     * breaking-news half may only use facts that existed at publication, and the
     * aftermath may only use facts that did not.
     *
     * Both sides are `Z`-normalized by {@link Utc}, so a plain string compare IS
     * a chronological compare. That is the payoff for rejecting zone offsets.
     *
     * The two boundary directions are deliberately asymmetric: a fact dated
     * EXACTLY at knownAt passes (the anchor commit is itself such a fact), while
     * a revelation dated exactly at knownAt fails, because a revelation knowable
     * at publication is not aftermath.
     */
    const notAfterKnownAt = (at: string, path: (string | number)[], label: string) => {
      if (at > knownAt) {
        ctx.issues.push({
          code: 'custom',
          input: ctx.value,
          path,
          message: `${label} is dated after knownAt (${at} > ${knownAt})`,
        })
      }
    }
    ctx.value.commits.forEach((commit, i) =>
      notAfterKnownAt(commit.committedAt, ['commits', i, 'committedAt'], `commit ${commit.sha.slice(0, 8)}`),
    )
    ctx.value.discussions.forEach((discussion, i) => {
      notAfterKnownAt(
        discussion.createdAt,
        ['discussions', i, 'createdAt'],
        `${discussion.kind} #${discussion.number}`,
      )
      discussion.quotes.forEach((quote, j) =>
        notAfterKnownAt(
          quote.createdAt,
          ['discussions', i, 'quotes', j, 'createdAt'],
          `comment by ${quote.author}`,
        ),
      )
    })
    // `fetchedAt` is deliberately NOT checked: it records when we retrieved the
    // body, which is always after publication and never a fact about the story.
    ctx.value.codeQuotes.forEach((quote, i) =>
      notAfterKnownAt(
        quote.atShaCommittedAt,
        ['codeQuotes', i, 'atShaCommittedAt'],
        `code quote ${quote.path}`,
      ),
    )
    ctx.value.revealedLater.forEach((entry, i) => {
      if (entry.at <= knownAt) {
        ctx.issues.push({
          code: 'custom',
          input: ctx.value,
          path: ['revealedLater', i, 'at'],
          message: `revelation is dated at or before knownAt (${entry.at} <= ${knownAt}); it was knowable at publication`,
        })
      }
    })

    /*
     * Uniqueness is enforced HERE, where the ids are minted, not on the article
     * that cites them. {@link incidentRefIndex} is a Map: two colliding entries
     * silently collapse into one, after which two aftermath citations pointing at
     * different claims would both "resolve" to the survivor.
     */
    const seen = new Map<string, number>()
    ctx.value.revealedLater.forEach((entry, i) => {
      const ref = revealedRefFor(entry)
      const first = seen.get(ref)
      if (first === undefined) {
        seen.set(ref, i)
        return
      }
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: ['revealedLater', i],
        message: `duplicate revealed id ${ref}, already minted by revealedLater[${first}]`,
      })
    })
  })

/** One of the five content-addressed id forms; parsed by {@link parseFactRef}, never by an index. */
export const FactRef = z.string().min(1)

const Sentence = z.strictObject({ text: z.string().min(1), cites: z.array(FactRef) })

/*
 * A prose block's unit is the SENTENCE, because the spec puts each [n]
 * immediately after the sentence it supports. A flat `text` + `cites[]` cannot
 * express that mapping, so the renderer would have no choice but to cluster
 * markers at the paragraph end.
 */
const Block = z.discriminatedUnion('type', [
  z.strictObject({ type: z.literal('prose'), sentences: z.array(Sentence).min(1) }),
  z.strictObject({ type: z.literal('codeQuote'), ref: FactRef }),
  z.strictObject({ type: z.literal('personQuote'), ref: FactRef }),
  z.strictObject({ type: z.literal('diffBox') }),
  z.strictObject({ type: z.literal('timelineBox') }),
])

/**
 * Shape-only article schema. The rules that need the incident live in
 * {@link articleSchemaFor}; the one rule enforceable on the article alone is the
 * lede exemption, so it is checked here.
 */
export const Article = z
  .strictObject({
    incidentId: Slug,
    lang: z.enum(['en']),
    persona: z.enum(['desk']),
    title: z.string().min(1).max(120),
    titleCites: z.array(FactRef).min(1),
    dek: z.string().min(1).max(240),
    dekCites: z.array(FactRef).min(1),
    publishedAt: Utc,
    updatedAt: Utc,
    blocks: z.array(Block),
    aftermath: z.array(z.strictObject({ text: z.string().min(1), ref: FactRef })),
  })
  .check((ctx) => {
    // The lede is blocks[0] POSITIONALLY. There is no lede flag, because a flag
    // is a constraint the constrained party gets to remove: a writer allowed to
    // set `lede: true` is a writer allowed to exempt any paragraph from citation.
    ctx.value.blocks.forEach((b, i) => {
      if (b.type !== 'prose' || i === 0) return
      if (!b.sentences.some((s) => s.cites.length >= 1)) {
        ctx.issues.push({
          code: 'custom',
          input: ctx.value,
          path: ['blocks', i],
          message: `prose block ${i} is not the lede and carries no cited sentence`,
        })
      }
    })
    if (ctx.value.updatedAt < ctx.value.publishedAt) {
      ctx.issues.push({
        code: 'custom',
        input: ctx.value,
        path: ['updatedAt'],
        message: 'updatedAt is before publishedAt',
      })
    }
  })

/**
 * Binds the shape-only {@link Article} to one {@link Incident}. These rules need
 * both halves, which is why they cannot live on {@link Article}: a ref that parses
 * but points nowhere, or points at a commit where a code quote was required, is
 * only detectable against the fact-set the article claims to cite.
 *
 * Zod runs a later `.check()` only when the earlier ones left the value clean, so
 * one parse reports {@link Article}'s shape violation OR a pair violation, never
 * both. Any violation is a FAIL, so that costs a second message, not a missed defect.
 *
 * @param incident - the fact-set the article claims to be about
 * @returns an Article schema that additionally rejects unresolvable or miskinded refs
 * @example articleSchemaFor(incident).safeParse(article).success // false when a ref points nowhere
 */
export function articleSchemaFor(incident: Incident) {
  const index = incidentRefIndex(incident)
  const datedFactCount = datedFacts(incident).length

  return Article.check((ctx) => {
    const article = ctx.value
    const fail = (path: (string | number)[], message: string) =>
      ctx.issues.push({ code: 'custom', input: article, path, message })

    if (article.incidentId !== incident.id) {
      fail(['incidentId'], `article is about ${article.incidentId}, not ${incident.id}`)
    }

    /** Resolves one ref against the fact-set and, when given, insists on its kind. */
    const resolve = (ref: string, path: (string | number)[], expected?: FactRefParsed['kind']) => {
      const kind = index.get(ref)
      if (kind === undefined) {
        fail(path, `${ref} does not resolve to any fact in ${incident.id}`)
        return
      }
      if (expected !== undefined && kind !== expected) {
        fail(path, `${ref} resolves to a ${kind} fact where a ${expected} fact was required`)
      }
    }

    article.titleCites.forEach((ref, i) => resolve(ref, ['titleCites', i]))
    article.dekCites.forEach((ref, i) => resolve(ref, ['dekCites', i]))

    article.blocks.forEach((block, i) => {
      switch (block.type) {
        case 'prose':
          block.sentences.forEach((sentence, j) =>
            sentence.cites.forEach((ref, k) =>
              resolve(ref, ['blocks', i, 'sentences', j, 'cites', k]),
            ),
          )
          return
        case 'codeQuote':
          resolve(block.ref, ['blocks', i, 'ref'], 'code')
          return
        case 'personQuote': {
          resolve(block.ref, ['blocks', i, 'ref'], 'discussion')
          // A pull quote is a person's words, so it must cite the comment carrying
          // them; `discussion:{n}` asserts only that the thread exists.
          const parsed = parseFactRef(block.ref)
          if (parsed?.kind === 'discussion' && parsed.commentId === undefined) {
            fail(
              ['blocks', i, 'ref'],
              `${block.ref} names a thread, not the comment whose words are quoted`,
            )
          }
          return
        }
        // The refless blocks carry no FactRef, so the resolution rules above cannot
        // reach them; each needs the fact-set to hold its own precondition.
        case 'diffBox':
          if (incident.diff === null) {
            fail(['blocks', i], 'diffBox rendered against an incident with no diff')
          }
          return
        case 'timelineBox':
          if (datedFactCount < 2) {
            fail(['blocks', i], `timelineBox needs 2 dated facts, incident has ${datedFactCount}`)
          }
      }
    })

    article.aftermath.forEach((entry, i) => resolve(entry.ref, ['aftermath', i, 'ref'], 'revealed'))
  })
}

export type Incident = z.infer<typeof Incident>
export type Article = z.infer<typeof Article>
export type Block = z.infer<typeof Block>
export type Sentence = z.infer<typeof Sentence>
